services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=zaq1@WSX
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  book-store-book-svc:
    image: neeyo/book-store-book-svc:latest
    build: 
      context: .
      dockerfile: src/BookService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User ID=postgres;Password=zaq1@WSX;Database=books
      - IdentityServiceUrl=http://book-store-identity-svc
    ports:
      - 7001:80
    depends_on:
      - postgres
      - rabbitmq
  book-store-search-svc:
    image: neeyo/book-store-search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:password@mongodb
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
  book-store-cart-svc:
    image: neeyo/book-store-cart-svc:latest
    build: 
      context: .
      dockerfile: src/CartService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User ID=postgres;Password=zaq1@WSX;Database=carts
      - IdentityServiceUrl=http://book-store-identity-svc
    ports:
      - 7003:80
    depends_on:
      - postgres
      - rabbitmq
  book-store-purchase-svc:
    image: neeyo/book-store-purchase-svc:latest
    build: 
      context: .
      dockerfile: src/PurchaseService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:password@mongodb
      - IdentityServiceUrl=http://book-store-identity-svc
    ports:
      - 7004:80
    depends_on:
      - mongodb
      - rabbitmq
  book-store-identity-svc:
    image: neeyo/book-store-identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User ID=postgres;Password=zaq1@WSX;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  book-store-gateway-svc:
    image: neeyo/book-store-gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/DockerFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
  book-store-web-app:
    image: neeyo/book-store-web-app:latest
    build: 
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    ports:
      - 3000:3000
    environment:
      - AUTH_SECRET="f942Ie7ecRbG2tQolecSHlU/QxLBtKChE2JMxovhYbQ="
      - API_URL=http://book-store-gateway-svc
      - ID_URL=http://localhost:5000
      - AUTH_URL=http://localhost:3000
      - AUTH_URL_INTERNAL=http://web-app:3000
volumes:
  pgdata:
  mongoData: